litellm_settings:
  drop_params: true

general_settings:
  master_key: sk-1234
  database_url: postgresql://user:Test1234!@localhost:5432/litellm_db

server_settings:
  host: "127.0.0.1"
  port: 4000

model_list:
  - model_name: "Qwen/Qwen3-8B"
    litellm_params:
      model: huggingface/Qwen/Qwen3-8B
      api_key: os.environ/HUGGINGFACE_API_KEY